### PR TITLE
Deleting reporting status

### PR DESCRIPTION
**Pull request by jwestw**
All deleted now

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@jwestw I think that error is something to do with the data that's being pulled via API:

https://data.un.org/ws/rest/data/IAEG-SDGs,DF_SDG_GLH,1.3/...524.........../ALL/?detail=full&dimensionAtObservation=TIME_PERIOD

See some COMMENT_OBS attributes in this file

**Comment by LucyGwilliamAdmin** [comment]
I'm not really sure what we can do to fix it as the problem is with the source data but might be good to put comment on the sdg-build PR so Brock's aware of it, and he may have some suggestions

**Comment by LucyGwilliamAdmin** [comment]
@jwestw might be able to use the alter_data option here to remove the trailling space on the columns:

See this example:
https://github.com/sdg-kyrgyzstan/open-sdg-data-starter/blob/develop/scripts/check_and_build_data.py#L7

However, since in Nepal's case (and most other cases), the build.py and check.py files are separate you will need to add the option to both.

These files can both be found in the scripts folder.

**Comment by jwestw** [comment]
Passing the tests now.

**Pull request merged**
